language: node_js

node_js:
  - '11'

dist: trusty

sudo: false

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run jest

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | $(npm bin)/coveralls