language: node_js
node_js:
  - '11'

sudo: false
dist: trusty

git:
  depth: 3

cache: yarn

notifications:
  email: false
  slack:
    rooms:
      - secure: wUcWGf49eyiAXZBqOcU7yST+SXCnMo878+7PvKWyUn7GRVTaigia8jve3eCyH/IgbJDbnsdnOgRSgynHLIYaoMPb+KK4u7E02H+Pu0os1scm6j0/zO0J/xwIG9gfy18Km7Q5CDa7o7JdiT5Yk6K87zUtOmHEY1MWvVJYwR2CH8cXlHuRzEVz/WYLAXmZQDca0y9k0s+zl3Ag52luU8Acq+qh3lPbkwMsUDJoPesHlOTKc+WvNyw6NOZc5WWg6gP13W0ZSakZQy8biC3Ud59r2sxPFVY1+TbRx+dR/EzPKCxhmLsP0mteqSBRbW0WlPKz5LKqfE9lAYQ5P3QQtjF41zvPI0X2UL8pd1eoPi/dTrvzQ4tOnE6Y4Vt+IP+vqWcKYCCsv5vnaveAEped8hD/IDNKbmRRPxx7lW3m+curVsULLnK9uKBH1TDoVHAlHd/znXthB2NN03h7Qj/KD1B/IX/S/keU/CZrEOUq2eEVAWNRj9qehqTxsOfHzrisNzpn+awA9T9NErhQj5JDh63IbG1IOuPUsQZWyCaqcmAi8ZEoL/VmHzbejTis8gCm/5v4/Pj40r78zCQuMyoj15ekALLUz68kn6141HbjprlFY7WoTtqs2zkZg3l+kp67ZhU9xrkeB0Vru1s8mWTlZL/W9n66TiGMPw24Nf5+iAhwVr4=

branches:
  only:
    - master

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci

jobs:
  fast_finish: true
  include:
    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-lint.sh

    - stage: test
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-test.sh
